
package com.boot.tool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateEmailWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateEmailWebServiceSoap {


    /**
     * <br /><h3>��֤ Email ��ַ�Ƿ���ȷ</h3><p>�������EmailAddress = Email ��ַ��Ĭ��SMTP�˿�25����������ݣ� Byte �ֽڡ�����ֵ�� 0 = ��������֤��1 = �ʼ���ַ�Ϸ���2 = ֻ��������ȷ��3 = һ��δ֪����4 = �ʼ�������û���ҵ���5 = �����ʼ���ַ����6 = ����û���֤����������50��/24Сʱ����7 = ��ҵ�û�����ͨ����֤</p><br />
     * 
     * @param theEmail
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddress", action = "http://WebXml.com.cn/ValidateEmailAddress")
    @WebResult(name = "ValidateEmailAddressResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "ValidateEmailAddress", targetNamespace = "http://WebXml.com.cn/", className = "com.ValidateEmailAddress")
    @ResponseWrapper(localName = "ValidateEmailAddressResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.ValidateEmailAddressResponse")
    public short validateEmailAddress(
        @WebParam(name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        String theEmail);

    /**
     * <br /><h3>��֤ Email ��ַ�Ƿ���ȷ</h3><p>�������EmailAddress = Email ��ַ��theEmailPort = SMTP�˿ڣ�Integer����������ݣ� Byte �ֽڡ�����ֵͬ ValidateEmailAddress</p><br />
     * 
     * @param theEmail
     * @param theEmailPort
     * @return
     *     returns short
     */
    @WebMethod(operationName = "ValidateEmailAddressPro", action = "http://WebXml.com.cn/ValidateEmailAddressPro")
    @WebResult(name = "ValidateEmailAddressProResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "ValidateEmailAddressPro", targetNamespace = "http://WebXml.com.cn/", className = "com.ValidateEmailAddressPro")
    @ResponseWrapper(localName = "ValidateEmailAddressProResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.ValidateEmailAddressProResponse")
    public short validateEmailAddressPro(
        @WebParam(name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        String theEmail,
        @WebParam(name = "theEmailPort", targetNamespace = "http://WebXml.com.cn/")
        int theEmailPort);

}
