
package com.boot.tool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>Email��ַ��֤ WEB ����</strong>��ͨ����Ҹ�ĵ����ʼ�����ʼ���������ͨ�����ʼ�����������������жϵ����ʼ���ַ��ȷ��񡣴�Email��ַ��֤Web Service�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>����ӭ���������� QQ��8409035<br /><strong>ʹ�ñ�վ WEB ������ע�������ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateEmailWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://ws.webxml.com.cn/WebServices/ValidateEmailWebService.asmx?WSDL")
public class ValidateEmailWebService
    extends Service
{

    private final static URL VALIDATEEMAILWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATEEMAILWEBSERVICE_EXCEPTION;
    private final static QName VALIDATEEMAILWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ValidateEmailWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.webxml.com.cn/WebServices/ValidateEmailWebService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATEEMAILWEBSERVICE_WSDL_LOCATION = url;
        VALIDATEEMAILWEBSERVICE_EXCEPTION = e;
    }

    public ValidateEmailWebService() {
        super(__getWsdlLocation(), VALIDATEEMAILWEBSERVICE_QNAME);
    }

    public ValidateEmailWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATEEMAILWEBSERVICE_QNAME, features);
    }

    public ValidateEmailWebService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATEEMAILWEBSERVICE_QNAME);
    }

    public ValidateEmailWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATEEMAILWEBSERVICE_QNAME, features);
    }

    public ValidateEmailWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateEmailWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap"), ValidateEmailWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateEmailWebServiceSoap
     */
    @WebEndpoint(name = "ValidateEmailWebServiceSoap")
    public ValidateEmailWebServiceSoap getValidateEmailWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateEmailWebServiceSoap"), ValidateEmailWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATEEMAILWEBSERVICE_EXCEPTION!= null) {
            throw VALIDATEEMAILWEBSERVICE_EXCEPTION;
        }
        return VALIDATEEMAILWEBSERVICE_WSDL_LOCATION;
    }

}
